CONFIG_GPIO=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_MAIN_STACK_SIZE=2048

CONFIG_RTIO=y
CONFIG_RTIO_SYS_MEM_BLOCKS=y

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
# CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BUFFER_SIZE=16384
CONFIG_LOG_PRINTK=n
# CONFIG_PRINTK=n   # . . . we're setting this 'n' here but build says it ends up assigned 'y'

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y

CONFIG_RM3100=y
# CONFIG_ICM42688=y # . . . may not need this with correct Zephyr driver implementation
CONFIG_ORESAT_ICM42688_STREAM=y

# 2026-06-01
CONFIG_SHELL=y
CONFIG_SHELL_LOG_BACKEND=y
CONFIG_I2C_SHELL=y
