// clang-format off
/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode v1 to v2

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
*******************************************************************************/
#ifndef CO_OD_H_
#define CO_OD_H_

/*******************************************************************************
   CANopen DATA TYPES
*******************************************************************************/
   typedef bool_t       BOOLEAN;
   typedef uint8_t      UNSIGNED8;
   typedef uint16_t     UNSIGNED16;
   typedef uint32_t     UNSIGNED32;
   typedef uint64_t     UNSIGNED64;
   typedef int8_t       INTEGER8;
   typedef int16_t      INTEGER16;
   typedef int32_t      INTEGER32;
   typedef int64_t      INTEGER64;
   typedef float32_t    REAL32;
   typedef float64_t    REAL64;
   typedef char_t       VISIBLE_STRING;
   typedef oChar_t      OCTET_STRING;

   #ifdef DOMAIN
   #undef DOMAIN
   #endif

   typedef domain_t     DOMAIN;

#ifndef timeOfDay_t
    typedef union {
        unsigned long long ullValue;
        struct {
            unsigned long ms:28;
            unsigned reserved:4;
            unsigned days:16;
            unsigned reserved2:16;
        };
    }timeOfDay_t;
#endif

    typedef timeOfDay_t TIME_OF_DAY;
    typedef timeOfDay_t TIME_DIFFERENCE;
/*******************************************************************************
   FILE INFO:
      FileName:     adcs (5).xdd
      FileVersion:  
      CreationTime: 8:06PM
      CreationDate: 06-07-2026
      CreatedBy:    
*******************************************************************************/


/*******************************************************************************
   DEVICE INFO:
      VendorName:     PSAS
      VendorNumber:   0
      ProductName:    ADCS
      ProductNumber:  0
*******************************************************************************/


/*******************************************************************************
   FEATURES
*******************************************************************************/
  #define CO_NO_SYNC                     0   //Associated objects: 1005-1007
  #define CO_NO_EMERGENCY                1   //Associated objects: 1014, 1015
  #define CO_NO_TIME                     0   //Associated objects: 1012, 1013
  #define CO_NO_SDO_SERVER               1   //Associated objects: 1200-127F
  #define CO_NO_SDO_CLIENT               0   //Associated objects: 1280-12FF
  #define CO_NO_GFC                      0   //Associated objects: 1300
  #define CO_NO_SRDO                     0   //Associated objects: 1301-1341, 1381-13C0
  #define CO_NO_LSS_SERVER               0   //LSS Slave
  #define CO_NO_LSS_CLIENT               0   //LSS Master
  #define CO_NODE_GUARDING_SLAVE         0   //NG Slave
  #define CO_NODE_GUARDING_MASTER        0   //NG Master
  #define CO_NO_RPDO                     1   //Associated objects: 14xx, 16xx
  #define CO_NO_TPDO                     10   //Associated objects: 18xx, 1Axx
  #define CO_NO_NMT_MASTER               0
  #define CO_NO_TRACE                    0


/*******************************************************************************
   OBJECT DICTIONARY
*******************************************************************************/
   #define CO_OD_NoOfElements             54


/*******************************************************************************
   TYPE DEFINITIONS FOR RECORDS
*******************************************************************************/
/*1018      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     vendorID;
               UNSIGNED32     productCode;
               UNSIGNED32     revisionNumber;
               UNSIGNED32     serialNumber;
               }              OD_identity_t;
/*1200      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     COB_IDClientToServer;
               UNSIGNED32     COB_IDServerToClient;
               UNSIGNED8      node_id_od_sdo_client;
               }              OD_SDOServerParameter_t;
/*1400      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     cob_id;
               UNSIGNED8      transmission_type;
               //UNSIGNED8      inhibit_time;
               //UNSIGNED8      compatibility_entry;
               //UNSIGNED16     event_timer;
               //UNSIGNED8      sync_start_value;
               }              OD_RPDOCommunicationParameter_t;
/*1600      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     mapping_object_1;
               UNSIGNED32     mapping_object_2;
               UNSIGNED32     mapping_object_3;
               UNSIGNED32     mapping_object_4;
               UNSIGNED32     mapping_object_5;
               UNSIGNED32     mapping_object_6;
               UNSIGNED32     mapping_object_7;
               UNSIGNED32     mapping_object_8;
               }              OD_RPDOMappingParameter_t;
/*1800      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     cob_id;
               UNSIGNED8      transmission_type;
               UNSIGNED16     inhibit_time;
               UNSIGNED8      compatibilityEntry;
               UNSIGNED16     event_timer;
               UNSIGNED8      sync_start_value;
               }              OD_TPDOCommunicationParameter_t;
/*1A00      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED32     mapping_object_1;
               UNSIGNED32     mapping_object_2;
               UNSIGNED32     mapping_object_3;
               UNSIGNED32     mapping_object_4;
               UNSIGNED32     mapping_object_5;
               UNSIGNED32     mapping_object_6;
               UNSIGNED32     mapping_object_7;
               UNSIGNED32     mapping_object_8;
               }              OD_TPDOMappingParameter_t;
/*3002      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               VISIBLE_STRING hw_version[3];
               VISIBLE_STRING configs_version[32];
               VISIBLE_STRING olaf_version[5];
               VISIBLE_STRING fw_version[5];
               }              OD_versions_t;
/*3003      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               UNSIGNED8      reset;
               UNSIGNED32     uptime;
               INTEGER8       temperature;
               UNSIGNED16     vrefint;
               }              OD_system_t;
/*4000      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER16      pitch_rate;
               INTEGER16      yaw_rate;
               INTEGER16      roll_rate;
               UNSIGNED16     pitch_rate_raw;
               UNSIGNED16     yaw_rate_raw;
               UNSIGNED16     roll_rate_raw;
               }              OD_gyroscope_t;
/*4001      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER16      x;
               INTEGER16      y;
               INTEGER16      z;
               UNSIGNED16     X_raw;
               UNSIGNED16     Y_raw;
               UNSIGNED16     Z_raw;
               }              OD_accelerometer_t;
/*4003      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER16      x;
               INTEGER16      y;
               INTEGER16      z;
               }              OD_pos_z_magnetometer_1_t;
/*4004      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER16      x;
               INTEGER16      y;
               INTEGER16      z;
               }              OD_pos_z_magnetometer_2_t;
/*4005      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER16      x;
               INTEGER16      y;
               INTEGER16      z;
               }              OD_min_z_magnetometer_1_t;
/*4006      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER16      x;
               INTEGER16      y;
               INTEGER16      z;
               }              OD_min_z_magnetometer_2_t;
/*4007      */ typedef struct {
               UNSIGNED8      highest_index_supported;
               INTEGER32      current_x;
               INTEGER32      current_y;
               INTEGER32      current_z;
               INTEGER32      current_x_setpoint;
               INTEGER32      current_y_setpoint;
               INTEGER32      current_z_setpoint;
               INTEGER16      pwm_x;
               INTEGER16      pwm_y;
               INTEGER16      pwm_z;
               }              OD_magnetorquer_t;

/*******************************************************************************
   TYPE DEFINITIONS FOR OBJECT DICTIONARY INDEXES

   some of those are redundant with CO_SDO.h CO_ObjDicId_t <Common CiA301 object
   dictionary entries>
*******************************************************************************/
/*1000 */
        #define OD_1000_device_type                                 0x1000

/*1001 */
        #define OD_1001_errorRegister                               0x1001

/*1003 */
        #define OD_1003_preDefinedErrorField                        0x1003

        #define OD_1003_0_preDefinedErrorField_maxSubIndex          0
        #define OD_1003_1_preDefinedErrorField_error_1              1
        #define OD_1003_2_preDefinedErrorField_error_2              2
        #define OD_1003_3_preDefinedErrorField_error_3              3
        #define OD_1003_4_preDefinedErrorField_error_4              4
        #define OD_1003_5_preDefinedErrorField_error_5              5
        #define OD_1003_6_preDefinedErrorField_error_6              6
        #define OD_1003_7_preDefinedErrorField_error_7              7
        #define OD_1003_8_preDefinedErrorField_error_8              8

/*1014 */
        #define OD_1014_cob_id_emergency_message                    0x1014

/*1015 */
        #define OD_1015_inhibitTimeEMCY                             0x1015

/*1016 */
        #define OD_1016_consumerHeartbeatTime                       0x1016

        #define OD_1016_0_consumerHeartbeatTime_maxSubIndex         0
        #define OD_1016_1_consumerHeartbeatTime_consumerHeartbeatTime 1

/*1017 */
        #define OD_1017_producerHeartbeatTime                       0x1017

/*1018 */
        #define OD_1018_identity                                    0x1018

        #define OD_1018_0_identity_maxSubIndex                      0
        #define OD_1018_1_identity_vendorID                         1
        #define OD_1018_2_identity_productCode                      2
        #define OD_1018_3_identity_revisionNumber                   3
        #define OD_1018_4_identity_serialNumber                     4

/*1019 */
        #define OD_1019_synchronousCounterOverflowValue             0x1019

/*1029 */
        #define OD_1029_errorBehavior                               0x1029

        #define OD_1029_0_errorBehavior_maxSubIndex                 0
        #define OD_1029_1_errorBehavior_communicationError          1

/*1200 */
        #define OD_1200_SDOServerParameter                          0x1200

        #define OD_1200_0_SDOServerParameter_maxSubIndex            0
        #define OD_1200_1_SDOServerParameter_COB_IDClientToServer   1
        #define OD_1200_2_SDOServerParameter_COB_IDServerToClient   2
        #define OD_1200_3_SDOServerParameter_node_id_od_sdo_client  3

/*1400 */
        #define OD_1400_RPDOCommunicationParameter                  0x1400

        #define OD_1400_0_RPDOCommunicationParameter_maxSubIndex    0
        #define OD_1400_1_RPDOCommunicationParameter_cob_id         1
        #define OD_1400_2_RPDOCommunicationParameter_transmission_type 2
        #define OD_1400_3_RPDOCommunicationParameter_inhibit_time   3
        #define OD_1400_4_RPDOCommunicationParameter_compatibility_entry 4
        #define OD_1400_5_RPDOCommunicationParameter_event_timer    5
        #define OD_1400_6_RPDOCommunicationParameter_sync_start_value 6

/*1600 */
        #define OD_1600_RPDOMappingParameter                        0x1600

        #define OD_1600_0_RPDOMappingParameter_maxSubIndex          0
        #define OD_1600_1_RPDOMappingParameter_mapping_object_1     1
        #define OD_1600_2_RPDOMappingParameter_mapping_object_2     2
        #define OD_1600_3_RPDOMappingParameter_mapping_object_3     3
        #define OD_1600_4_RPDOMappingParameter_mapping_object_4     4
        #define OD_1600_5_RPDOMappingParameter_mapping_object_5     5
        #define OD_1600_6_RPDOMappingParameter_mapping_object_6     6
        #define OD_1600_7_RPDOMappingParameter_mapping_object_7     7
        #define OD_1600_8_RPDOMappingParameter_mapping_object_8     8

/*1800 */
        #define OD_1800_TPDOCommunicationParameter                  0x1800

        #define OD_1800_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1800_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1800_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1800_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1800_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1800_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1800_6_TPDOCommunicationParameter_sync_start_value 6

/*1801 */
        #define OD_1801_TPDOCommunicationParameter                  0x1801

        #define OD_1801_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1801_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1801_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1801_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1801_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1801_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1801_6_TPDOCommunicationParameter_sync_start_value 6

/*1802 */
        #define OD_1802_TPDOCommunicationParameter                  0x1802

        #define OD_1802_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1802_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1802_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1802_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1802_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1802_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1802_6_TPDOCommunicationParameter_sync_start_value 6

/*1803 */
        #define OD_1803_TPDOCommunicationParameter                  0x1803

        #define OD_1803_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1803_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1803_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1803_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1803_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1803_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1803_6_TPDOCommunicationParameter_sync_start_value 6

/*1804 */
        #define OD_1804_TPDOCommunicationParameter                  0x1804

        #define OD_1804_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1804_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1804_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1804_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1804_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1804_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1804_6_TPDOCommunicationParameter_sync_start_value 6

/*1805 */
        #define OD_1805_TPDOCommunicationParameter                  0x1805

        #define OD_1805_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1805_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1805_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1805_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1805_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1805_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1805_6_TPDOCommunicationParameter_sync_start_value 6

/*1806 */
        #define OD_1806_TPDOCommunicationParameter                  0x1806

        #define OD_1806_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1806_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1806_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1806_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1806_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1806_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1806_6_TPDOCommunicationParameter_sync_start_value 6

/*1807 */
        #define OD_1807_TPDOCommunicationParameter                  0x1807

        #define OD_1807_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1807_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1807_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1807_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1807_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1807_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1807_6_TPDOCommunicationParameter_sync_start_value 6

/*1808 */
        #define OD_1808_TPDOCommunicationParameter                  0x1808

        #define OD_1808_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1808_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1808_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1808_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1808_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1808_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1808_6_TPDOCommunicationParameter_sync_start_value 6

/*1809 */
        #define OD_1809_TPDOCommunicationParameter                  0x1809

        #define OD_1809_0_TPDOCommunicationParameter_maxSubIndex    0
        #define OD_1809_1_TPDOCommunicationParameter_cob_id         1
        #define OD_1809_2_TPDOCommunicationParameter_transmission_type 2
        #define OD_1809_3_TPDOCommunicationParameter_inhibit_time   3
        #define OD_1809_4_TPDOCommunicationParameter_compatibilityEntry 4
        #define OD_1809_5_TPDOCommunicationParameter_event_timer    5
        #define OD_1809_6_TPDOCommunicationParameter_sync_start_value 6

/*1A00 */
        #define OD_1A00_TPDOMappingParameter                        0x1A00

        #define OD_1A00_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A00_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A00_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A00_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A00_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A00_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A00_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A00_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A00_8_TPDOMappingParameter_mapping_object_8     8

/*1A01 */
        #define OD_1A01_TPDOMappingParameter                        0x1A01

        #define OD_1A01_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A01_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A01_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A01_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A01_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A01_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A01_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A01_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A01_8_TPDOMappingParameter_mapping_object_8     8

/*1A02 */
        #define OD_1A02_TPDOMappingParameter                        0x1A02

        #define OD_1A02_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A02_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A02_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A02_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A02_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A02_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A02_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A02_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A02_8_TPDOMappingParameter_mapping_object_8     8

/*1A03 */
        #define OD_1A03_TPDOMappingParameter                        0x1A03

        #define OD_1A03_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A03_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A03_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A03_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A03_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A03_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A03_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A03_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A03_8_TPDOMappingParameter_mapping_object_8     8

/*1A04 */
        #define OD_1A04_TPDOMappingParameter                        0x1A04

        #define OD_1A04_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A04_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A04_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A04_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A04_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A04_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A04_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A04_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A04_8_TPDOMappingParameter_mapping_object_8     8

/*1A05 */
        #define OD_1A05_TPDOMappingParameter                        0x1A05

        #define OD_1A05_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A05_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A05_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A05_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A05_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A05_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A05_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A05_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A05_8_TPDOMappingParameter_mapping_object_8     8

/*1A06 */
        #define OD_1A06_TPDOMappingParameter                        0x1A06

        #define OD_1A06_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A06_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A06_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A06_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A06_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A06_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A06_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A06_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A06_8_TPDOMappingParameter_mapping_object_8     8

/*1A07 */
        #define OD_1A07_TPDOMappingParameter                        0x1A07

        #define OD_1A07_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A07_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A07_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A07_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A07_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A07_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A07_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A07_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A07_8_TPDOMappingParameter_mapping_object_8     8

/*1A08 */
        #define OD_1A08_TPDOMappingParameter                        0x1A08

        #define OD_1A08_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A08_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A08_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A08_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A08_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A08_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A08_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A08_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A08_8_TPDOMappingParameter_mapping_object_8     8

/*1A09 */
        #define OD_1A09_TPDOMappingParameter                        0x1A09

        #define OD_1A09_0_TPDOMappingParameter_maxSubIndex          0
        #define OD_1A09_1_TPDOMappingParameter_mapping_object_1     1
        #define OD_1A09_2_TPDOMappingParameter_mapping_object_2     2
        #define OD_1A09_3_TPDOMappingParameter_mapping_object_3     3
        #define OD_1A09_4_TPDOMappingParameter_mapping_object_4     4
        #define OD_1A09_5_TPDOMappingParameter_mapping_object_5     5
        #define OD_1A09_6_TPDOMappingParameter_mapping_object_6     6
        #define OD_1A09_7_TPDOMappingParameter_mapping_object_7     7
        #define OD_1A09_8_TPDOMappingParameter_mapping_object_8     8

/*1F80 */
        #define OD_1F80_NMTStartup                                  0x1F80

/*2010 */
        #define OD_2010_scet                                        0x2010

/*2011 */
        #define OD_2011_utc                                         0x2011

/*2100 */
        #define OD_2100_errorStatusBits                             0x2100

/*3000 */
        #define OD_3000_satellite_id                                0x3000

/*3001 */
        #define OD_3001_flight_mode                                 0x3001

/*3002 */
        #define OD_3002_versions                                    0x3002

        #define OD_3002_0_versions_maxSubIndex                      0
        #define OD_3002_1_versions_hw_version                       1
        #define OD_3002_2_versions_configs_version                  2
        #define OD_3002_3_versions_olaf_version                     3
        #define OD_3002_4_versions_fw_version                       4

/*3003 */
        #define OD_3003_system                                      0x3003

        #define OD_3003_0_system_maxSubIndex                        0
        #define OD_3003_1_system_reset                              1
        #define OD_3003_5_system_uptime                             5
        #define OD_3003_7_system_temperature                        7
        #define OD_3003_8_system_vrefint                            8

/*3009 */
        #define OD_3009_board_id                                    0x3009

/*4000 */
        #define OD_4000_gyroscope                                   0x4000

        #define OD_4000_0_gyroscope_maxSubIndex                     0
        #define OD_4000_1_gyroscope_pitch_rate                      1
        #define OD_4000_2_gyroscope_yaw_rate                        2
        #define OD_4000_3_gyroscope_roll_rate                       3
        #define OD_4000_4_gyroscope_pitch_rate_raw                  4
        #define OD_4000_5_gyroscope_yaw_rate_raw                    5
        #define OD_4000_6_gyroscope_roll_rate_raw                   6

/*4001 */
        #define OD_4001_accelerometer                               0x4001

        #define OD_4001_0_accelerometer_maxSubIndex                 0
        #define OD_4001_1_accelerometer_x                           1
        #define OD_4001_2_accelerometer_y                           2
        #define OD_4001_3_accelerometer_z                           3
        #define OD_4001_4_accelerometer_X_raw                       4
        #define OD_4001_5_accelerometer_Y_raw                       5
        #define OD_4001_6_accelerometer_Z_raw                       6

/*4002 */
        #define OD_4002_temperature                                 0x4002

/*4003 */
        #define OD_4003_pos_z_magnetometer_1                        0x4003

        #define OD_4003_0_pos_z_magnetometer_1_maxSubIndex          0
        #define OD_4003_1_pos_z_magnetometer_1_x                    1
        #define OD_4003_2_pos_z_magnetometer_1_y                    2
        #define OD_4003_3_pos_z_magnetometer_1_z                    3

/*4004 */
        #define OD_4004_pos_z_magnetometer_2                        0x4004

        #define OD_4004_0_pos_z_magnetometer_2_maxSubIndex          0
        #define OD_4004_1_pos_z_magnetometer_2_x                    1
        #define OD_4004_2_pos_z_magnetometer_2_y                    2
        #define OD_4004_3_pos_z_magnetometer_2_z                    3

/*4005 */
        #define OD_4005_min_z_magnetometer_1                        0x4005

        #define OD_4005_0_min_z_magnetometer_1_maxSubIndex          0
        #define OD_4005_1_min_z_magnetometer_1_x                    1
        #define OD_4005_2_min_z_magnetometer_1_y                    2
        #define OD_4005_3_min_z_magnetometer_1_z                    3

/*4006 */
        #define OD_4006_min_z_magnetometer_2                        0x4006

        #define OD_4006_0_min_z_magnetometer_2_maxSubIndex          0
        #define OD_4006_1_min_z_magnetometer_2_x                    1
        #define OD_4006_2_min_z_magnetometer_2_y                    2
        #define OD_4006_3_min_z_magnetometer_2_z                    3

/*4007 */
        #define OD_4007_magnetorquer                                0x4007

        #define OD_4007_0_magnetorquer_maxSubIndex                  0
        #define OD_4007_1_magnetorquer_current_x                    1
        #define OD_4007_2_magnetorquer_current_y                    2
        #define OD_4007_3_magnetorquer_current_z                    3
        #define OD_4007_4_magnetorquer_current_x_setpoint           4
        #define OD_4007_5_magnetorquer_current_y_setpoint           5
        #define OD_4007_6_magnetorquer_current_z_setpoint           6
        #define OD_4007_7_magnetorquer_pwm_x                        7
        #define OD_4007_8_magnetorquer_pwm_y                        8
        #define OD_4007_9_magnetorquer_pwm_z                        9

/*******************************************************************************
   STRUCTURES FOR VARIABLES IN DIFFERENT MEMORY LOCATIONS
*******************************************************************************/
#define  CO_OD_FIRST_LAST_WORD     0x55 //Any value from 0x01 to 0xFE. If changed, EEPROM will be reinitialized.

/***** Structure for RAM variables ********************************************/
struct sCO_OD_RAM{
               UNSIGNED32     FirstWord;

/*1000      */ UNSIGNED32     device_type;
/*1001      */ UNSIGNED8      errorRegister;
/*1003      */ UNSIGNED32      preDefinedErrorField[8];
/*1014      */ UNSIGNED32     cob_id_emergency_message;
/*1015      */ UNSIGNED16     inhibitTimeEMCY;
/*1017      */ UNSIGNED16     producerHeartbeatTime;
/*1018      */ OD_identity_t   identity;
/*1019      */ UNSIGNED8      synchronousCounterOverflowValue;
/*1200      */ OD_SDOServerParameter_t SDOServerParameter[1];
/*1802      */ OD_TPDOCommunicationParameter_t TPDOCommunicationParameter[10];

// firmware update OD indexes:
/*1F50      */ DOMAIN         program_data[1];
/*1F51      */ UNSIGNED8      program_control[1];
/*1F56      */ UNSIGNED32     program_software_id[1];
/*1F57      */ UNSIGNED32     flash_status[1];
// firmware update OD indexes.

/*1F80      */ UNSIGNED32     NMTStartup;
/*2010      */ UNSIGNED64     scet;
/*2011      */ UNSIGNED64     utc;
/*2100      */ OCTET_STRING   errorStatusBits[32];
/*3000      */ UNSIGNED8      satellite_id;
/*3001      */ BOOLEAN        flight_mode;
/*3002      */ OD_versions_t   versions;
/*3003      */ OD_system_t     system;
/*3009      */ UNSIGNED8      board_id;
/*4000      */ OD_gyroscope_t  gyroscope;
/*4001      */ OD_accelerometer_t accelerometer;
/*4002      */ INTEGER8       temperature;
/*4003      */ OD_pos_z_magnetometer_1_t pos_z_magnetometer_1;
/*4004      */ OD_pos_z_magnetometer_2_t pos_z_magnetometer_2;
/*4005      */ OD_min_z_magnetometer_1_t min_z_magnetometer_1;
/*4006      */ OD_min_z_magnetometer_2_t min_z_magnetometer_2;
/*4007      */ OD_magnetorquer_t magnetorquer;

               UNSIGNED32     LastWord;
};

/***** Structure for PERSIST_COMM variables ********************************************/
struct sCO_OD_PERSIST_COMM{
               UNSIGNED32     FirstWord;

/*1016      */ UNSIGNED32      consumerHeartbeatTime[1];
/*1029      */ UNSIGNED8       errorBehavior[1];
/*1400      */ OD_RPDOCommunicationParameter_t RPDOCommunicationParameter[1];
/*1600      */ OD_RPDOMappingParameter_t RPDOMappingParameter[1];
/*1800      */ OD_TPDOCommunicationParameter_t TPDOCommunicationParameter[10];
/*1A00      */ OD_TPDOMappingParameter_t TPDOMappingParameter[10];

               UNSIGNED32     LastWord;
};

/***** Structure for ROM variables ********************************************/
struct sCO_OD_ROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Structure for EEPROM variables ********************************************/
struct sCO_OD_EEPROM{
               UNSIGNED32     FirstWord;


               UNSIGNED32     LastWord;
};

/***** Declaration of Object Dictionary variables *****************************/
extern struct sCO_OD_RAM CO_OD_RAM;

extern struct sCO_OD_PERSIST_COMM CO_OD_PERSIST_COMM;

extern struct sCO_OD_ROM CO_OD_ROM;

extern struct sCO_OD_EEPROM CO_OD_EEPROM;

/*******************************************************************************
   ALIASES FOR OBJECT DICTIONARY VARIABLES
*******************************************************************************/
/*1000, Data Type: UNSIGNED32 */
        #define OD_device_type_idx                                  0x1000
        #define OD_device_type                                      CO_OD_RAM.device_type

/*1001, Data Type: UNSIGNED8 */
        #define OD_errorRegister_idx                                0x1001
        #define OD_errorRegister                                    CO_OD_RAM.errorRegister

/*1003, Data Type: UNSIGNED32, Array[8] */
        #define OD_preDefinedErrorField_idx                         0x1003
        #define OD_preDefinedErrorField                             CO_OD_RAM.preDefinedErrorField
        #define ODL_preDefinedErrorField_arrayLength                8
        #define ODA_preDefinedErrorField_error_1                    0
        #define ODA_preDefinedErrorField_error_2                    1
        #define ODA_preDefinedErrorField_error_3                    2
        #define ODA_preDefinedErrorField_error_4                    3
        #define ODA_preDefinedErrorField_error_5                    4
        #define ODA_preDefinedErrorField_error_6                    5
        #define ODA_preDefinedErrorField_error_7                    6
        #define ODA_preDefinedErrorField_error_8                    7

/*1014, Data Type: UNSIGNED32 */
        #define OD_cob_id_emergency_message_idx                     0x1014
        #define OD_cob_id_emergency_message                         CO_OD_RAM.cob_id_emergency_message

/*1015, Data Type: UNSIGNED16 */
        #define OD_inhibitTimeEMCY_idx                              0x1015
        #define OD_inhibitTimeEMCY                                  CO_OD_RAM.inhibitTimeEMCY

/*1016, Data Type: UNSIGNED32, Array[1] */
        #define OD_consumerHeartbeatTime_idx                        0x1016
        #define OD_consumerHeartbeatTime                            CO_OD_PERSIST_COMM.consumerHeartbeatTime
        #define ODL_consumerHeartbeatTime_arrayLength               1
        #define ODA_consumerHeartbeatTime_consumerHeartbeatTime     0

/*1017, Data Type: UNSIGNED16 */
        #define OD_producerHeartbeatTime_idx                        0x1017
        #define OD_producerHeartbeatTime                            CO_OD_RAM.producerHeartbeatTime

/*1018, Data Type: identity_t */
        #define OD_identity_idx                                     0x1018
        #define OD_identity                                         CO_OD_RAM.identity

/*1019, Data Type: UNSIGNED8 */
        #define OD_synchronousCounterOverflowValue_idx              0x1019
        #define OD_synchronousCounterOverflowValue                  CO_OD_RAM.synchronousCounterOverflowValue

/*1029, Data Type: UNSIGNED8, Array[1] */
        #define OD_errorBehavior_idx                                0x1029
        #define OD_errorBehavior                                    CO_OD_PERSIST_COMM.errorBehavior
        #define ODL_errorBehavior_arrayLength                       1
        #define ODA_errorBehavior_communicationError                0

/*1200, Data Type: SDOServerParameter_t */
        #define OD_SDOServerParameter_idx                           0x1200
        #define OD_SDOServerParameter                               CO_OD_RAM.SDOServerParameter

/*1400, Data Type: RPDOCommunicationParameter_t */
        #define OD_RPDOCommunicationParameter_idx                   0x1400
        #define OD_RPDOCommunicationParameter                       CO_OD_PERSIST_COMM.RPDOCommunicationParameter

/*1600, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter_idx                         0x1600
        #define OD_RPDOMappingParameter                             CO_OD_PERSIST_COMM.RPDOMappingParameter

/*1800, Data Type: TPDOCommunicationParameter_t */
        #define OD_TPDOCommunicationParameter_idx                   0x1800
        #define OD_TPDOCommunicationParameter                       CO_OD_PERSIST_COMM.TPDOCommunicationParameter

/*1A00, Data Type: TPDOMappingParameter_t */
        #define OD_TPDOMappingParameter_idx                         0x1A00
        #define OD_TPDOMappingParameter                             CO_OD_PERSIST_COMM.TPDOMappingParameter

// firmware update OD indexes:
/*1F50, Data Type: DOMAIN, Array[1] */
#define OD_program_data                           CO_OD_RAM.program_data
#define ODL_program_data_arrayLength              1
#define ODA_program_data_programData              0

/*1F51, Data Type: UNSIGNED8, Array[1] */
#define OD_program_control                        CO_OD_RAM.program_control
#define ODL_program_control_arrayLength           1
#define ODA_program_control_programControl        0

/*1F56, Data Type: UNSIGNED32, Array[1] */
#define OD_program_software_id                    CO_OD_RAM.program_software_id
#define ODL_program_software_id_arrayLength       1
#define ODA_program_software_id_programSoftwareIdentification 0

/*1F57, Data Type: UNSIGNED32, Array[1] */
#define OD_flash_status                           CO_OD_RAM.flash_status
#define ODL_flash_status_arrayLength              1
#define ODA_flash_status_flashStatusIdentification 0
// firmware update OD indexes.

/*1F80, Data Type: UNSIGNED32 */
        #define OD_NMTStartup_idx                                   0x1F80
        #define OD_NMTStartup                                       CO_OD_RAM.NMTStartup

/*2010, Data Type: UNSIGNED64 */
        #define OD_scet_idx                                         0x2010
        #define OD_scet                                             CO_OD_RAM.scet

/*2011, Data Type: UNSIGNED64 */
        #define OD_utc_idx                                          0x2011
        #define OD_utc                                              CO_OD_RAM.utc

/*2100, Data Type: OCTET_STRING */
        #define OD_errorStatusBits_idx                              0x2100
        #define OD_errorStatusBits                                  CO_OD_RAM.errorStatusBits
        #define ODL_errorStatusBits_stringLength                    32

/*3000, Data Type: UNSIGNED8 */
        #define OD_satellite_id_idx                                 0x3000
        #define OD_satellite_id                                     CO_OD_RAM.satellite_id

/*3001, Data Type: BOOLEAN */
        #define OD_flight_mode_idx                                  0x3001
        #define OD_flight_mode                                      CO_OD_RAM.flight_mode

/*3002, Data Type: versions_t */
        #define OD_versions_idx                                     0x3002
        #define OD_versions                                         CO_OD_RAM.versions

/*3003, Data Type: system_t */
        #define OD_system_idx                                       0x3003
        #define OD_system                                           CO_OD_RAM.system

/*3009, Data Type: UNSIGNED8 */
        #define OD_board_id_idx                                     0x3009
        #define OD_board_id                                         CO_OD_RAM.board_id

/*4000, Data Type: gyroscope_t */
        #define OD_gyroscope_idx                                    0x4000
        #define OD_gyroscope                                        CO_OD_RAM.gyroscope

/*4001, Data Type: accelerometer_t */
        #define OD_accelerometer_idx                                0x4001
        #define OD_accelerometer                                    CO_OD_RAM.accelerometer

/*4002, Data Type: INTEGER8 */
        #define OD_temperature_idx                                  0x4002
        #define OD_temperature                                      CO_OD_RAM.temperature

/*4003, Data Type: pos_z_magnetometer_1_t */
        #define OD_pos_z_magnetometer_1_idx                         0x4003
        #define OD_pos_z_magnetometer_1                             CO_OD_RAM.pos_z_magnetometer_1

/*4004, Data Type: pos_z_magnetometer_2_t */
        #define OD_pos_z_magnetometer_2_idx                         0x4004
        #define OD_pos_z_magnetometer_2                             CO_OD_RAM.pos_z_magnetometer_2

/*4005, Data Type: min_z_magnetometer_1_t */
        #define OD_min_z_magnetometer_1_idx                         0x4005
        #define OD_min_z_magnetometer_1                             CO_OD_RAM.min_z_magnetometer_1

/*4006, Data Type: min_z_magnetometer_2_t */
        #define OD_min_z_magnetometer_2_idx                         0x4006
        #define OD_min_z_magnetometer_2                             CO_OD_RAM.min_z_magnetometer_2

/*4007, Data Type: magnetorquer_t */
        #define OD_magnetorquer_idx                                 0x4007
        #define OD_magnetorquer                                     CO_OD_RAM.magnetorquer

#endif
// clang-format on
